In [18]:
from numpy import array ,random,dot
from scipy.special import softmax

# encoder representation of four words 
word1 = array([1,0,0])
word2 = array([0,1,0])
word3 = array([0,0,1])
word4 = array([1,0,0])

# stacking the word into single array
words = array([word1,word2,word3,word4])
print("WORDS \n",words)

WORDS 
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]


In [19]:
# generation weights matrices 
random.seed(42)
W_Q = random.randint(3,size=(3,3))
W_k = random.randint(3,size=(3,3))
W_V = random.randint(3,size=(3,3))

# generating the  queries , keys , values
Q =  words @ W_Q
k =  words @ W_k
V =  words @ W_V

print("QUERY \n",Q)
print("KEYS \n" ,k)
print("VALUES \n" ,V)

QUERY 
 [[2 0 2]
 [2 0 0]
 [2 1 2]
 [2 0 2]]
KEYS 
 [[2 2 2]
 [0 2 1]
 [0 1 1]
 [2 2 2]]
VALUES 
 [[1 1 0]
 [0 1 1]
 [0 0 0]
 [1 1 0]]


In [21]:
# scoring the query ,  keys , and values
scores = Q @ k.transpose()
print("SCORES-------\n",scores)
print("SHAPE OF K-----\n",k.shape[1])
weights = softmax(scores/k.shape[1]**0.5,axis=1) # computing the weights
print("WIEGHTS-------\n",weights)

# computing the attention by a weighted sum of the value vectors
attention = weights @ V
print("ATTENTION-----------\n",attention)

SCORES-------
 [[ 8  2  2  8]
 [ 4  0  0  4]
 [10  4  3 10]
 [ 8  2  2  8]]
SHAPE OF K-----
 3
WIEGHTS-------
 [[0.48482445 0.01517555 0.01517555 0.48482445]
 [0.45482632 0.04517368 0.04517368 0.45482632]
 [0.48807319 0.01527723 0.00857639 0.48807319]
 [0.48482445 0.01517555 0.01517555 0.48482445]]
ATTENTION-----------
 [[0.96964891 0.98482445 0.01517555]
 [0.90965265 0.95482632 0.04517368]
 [0.97614637 0.99142361 0.01527723]
 [0.96964891 0.98482445 0.01517555]]
